version: '3.8'

services:
  products-postgresql:
    container_name: product-store-postgresql
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AXEe263eqPFqwy4z
    ports:
      - "5432:5432"
    volumes:
      - product-store-postgresql-local:/var/lib/postgresql/data

  products-prometheus:
    container_name: product-store-prometheus
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  products-grafana:
    container_name: product-store-grafana
    image: grafana/grafana:7.3.7
    ports:
      - "3000:3000"

volumes:
  product-store-postgresql-local:

